name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  hadolint:
    name: Lint Containerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
      with:
        dockerfile: Containerfile

  shellcheck:
    name: Lint scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        # Differential ShellCheck requires full git history
        fetch-depth: 0

    - name: Differential ShellCheck
      uses: redhat-plumbers-in-action/differential-shellcheck@f51c7c0d32777d00de777131d25918617a246415  # v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build image (no push)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Buildah Action
      uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3
      with:
        image: img-okd-tools
        tags: ci
        containerfiles: |
          ./Containerfile
